// Generated by gencpp from file waypoint_follower/StopCar.msg
// DO NOT EDIT!


#ifndef WAYPOINT_FOLLOWER_MESSAGE_STOPCAR_H
#define WAYPOINT_FOLLOWER_MESSAGE_STOPCAR_H

#include <ros/service_traits.h>


#include <waypoint_follower/StopCarRequest.h>
#include <waypoint_follower/StopCarResponse.h>


namespace waypoint_follower
{

struct StopCar
{

typedef StopCarRequest Request;
typedef StopCarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopCar
} // namespace waypoint_follower


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waypoint_follower::StopCar > {
  static const char* value()
  {
    return "2dd673dc8b4d940385d9faeea3f88f0a";
  }

  static const char* value(const ::waypoint_follower::StopCar&) { return value(); }
};

template<>
struct DataType< ::waypoint_follower::StopCar > {
  static const char* value()
  {
    return "waypoint_follower/StopCar";
  }

  static const char* value(const ::waypoint_follower::StopCar&) { return value(); }
};


// service_traits::MD5Sum< ::waypoint_follower::StopCarRequest> should match
// service_traits::MD5Sum< ::waypoint_follower::StopCar >
template<>
struct MD5Sum< ::waypoint_follower::StopCarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waypoint_follower::StopCar >::value();
  }
  static const char* value(const ::waypoint_follower::StopCarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoint_follower::StopCarRequest> should match
// service_traits::DataType< ::waypoint_follower::StopCar >
template<>
struct DataType< ::waypoint_follower::StopCarRequest>
{
  static const char* value()
  {
    return DataType< ::waypoint_follower::StopCar >::value();
  }
  static const char* value(const ::waypoint_follower::StopCarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waypoint_follower::StopCarResponse> should match
// service_traits::MD5Sum< ::waypoint_follower::StopCar >
template<>
struct MD5Sum< ::waypoint_follower::StopCarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waypoint_follower::StopCar >::value();
  }
  static const char* value(const ::waypoint_follower::StopCarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoint_follower::StopCarResponse> should match
// service_traits::DataType< ::waypoint_follower::StopCar >
template<>
struct DataType< ::waypoint_follower::StopCarResponse>
{
  static const char* value()
  {
    return DataType< ::waypoint_follower::StopCar >::value();
  }
  static const char* value(const ::waypoint_follower::StopCarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAYPOINT_FOLLOWER_MESSAGE_STOPCAR_H
