// Generated by gencpp from file waypoint_follower/StopCarRequest.msg
// DO NOT EDIT!


#ifndef WAYPOINT_FOLLOWER_MESSAGE_STOPCARREQUEST_H
#define WAYPOINT_FOLLOWER_MESSAGE_STOPCARREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace waypoint_follower
{
template <class ContainerAllocator>
struct StopCarRequest_
{
  typedef StopCarRequest_<ContainerAllocator> Type;

  StopCarRequest_()
    : a(0.0)
    , b(0.0)  {
    }
  StopCarRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)  {
  (void)_alloc;
    }



   typedef float _a_type;
  _a_type a;

   typedef float _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::waypoint_follower::StopCarRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoint_follower::StopCarRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopCarRequest_

typedef ::waypoint_follower::StopCarRequest_<std::allocator<void> > StopCarRequest;

typedef boost::shared_ptr< ::waypoint_follower::StopCarRequest > StopCarRequestPtr;
typedef boost::shared_ptr< ::waypoint_follower::StopCarRequest const> StopCarRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoint_follower::StopCarRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoint_follower::StopCarRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::waypoint_follower::StopCarRequest_<ContainerAllocator1> & lhs, const ::waypoint_follower::StopCarRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::waypoint_follower::StopCarRequest_<ContainerAllocator1> & lhs, const ::waypoint_follower::StopCarRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace waypoint_follower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_follower::StopCarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_follower::StopCarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_follower::StopCarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_follower::StopCarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_follower::StopCarRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_follower::StopCarRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoint_follower::StopCarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f6326d24b4937f854196fd3a843f42e";
  }

  static const char* value(const ::waypoint_follower::StopCarRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f6326d24b4937f8ULL;
  static const uint64_t static_value2 = 0x54196fd3a843f42eULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoint_follower::StopCarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoint_follower/StopCarRequest";
  }

  static const char* value(const ::waypoint_follower::StopCarRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoint_follower::StopCarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a\n"
"float32 b\n"
;
  }

  static const char* value(const ::waypoint_follower::StopCarRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoint_follower::StopCarRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopCarRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoint_follower::StopCarRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waypoint_follower::StopCarRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINT_FOLLOWER_MESSAGE_STOPCARREQUEST_H
